services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./database/migrations/versions:/app/migrations/versions
    depends_on:
      - redis
    networks:
      - my-network

  psql:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    depends_on:
      - psql
    networks:
      - my-network

volumes:
  psql-data:
    driver: local
  redis-data:
    driver: local

networks:
  my-network:
    driver: bridge